### PR TITLE
Update eventmachine for Ruby 2.2

### PR DESCRIPTION
**Pull request by se3000**
Fixes https://github.com/coinbase/toshi/issues/160 and makes Toshi Ruby 2.2.0 compatible.

### CODE REVIEW

**Comment by aalness** [comment]
@se3000 did you happen to test if websockets were affected?

**Comment by se3000** [comment]
I did not. Just ran the test suite against 2.1.2 and 2.2.0.

**Comment by aalness** [comment]
Mind starting a sync of testnet and monitoring the "blocks" tab in the UI to verify websocket behvior is unaffected? I vaguely recall trying 2.2 before and noticing EM acting funny wrt them.

**Comment by se3000** [comment]
Sure, I'll check it out this weekend.

**Comment by se3000** [comment]
After updating faye-websocket the blocks tab works.

The transactions tab doesn't seem to update, maybe because it doesn't know about the inputs for most of the unconfirmed transactions yet? I only have a small part of the testnet block chain on this computer.

**Comment by aalness** [comment]
Yeah. If the blocks tab works then I wouldn't worry about it. It's likely every transaction looks like an orphan to your node (the websocket won't announce orphans.)

**Comment by aalness** [comment]
One more thing: mind adding 2.2 to the travis test matrix, please?

**Comment by se3000** [comment]
Rebased and added it.

Was thinking about an integration test for websockets, seems like a separate issue.

**Comment by aalness** [comment]
:+1: nice

**Pull request merged**
